const styleTag=document.getElementById("styles_js"),body=document.getElementsByTagName("body")[0],quoteBkgd=document.getElementsByClassName("container")[0],quoteCot=document.getElementById("quote-box"),allBtns=Array.from(document.getElementsByClassName("btn")),newBtn=document.getElementById("load-quote"),stopBtn=document.getElementById("stop-btn"),startBtn=document.getElementById("start-btn"),bellaBtn=document.getElementById("developer");let interval,history=[];function getRandomVal(t,e){let o=Math.round(Math.random()*t+0);return o===history[e]&&++o>t&&(o-=2),history[e]=o,o}function startTimer(){interval=window.setInterval(function(){printQuote()},1e4),startBtn.style.display="none",stopBtn.style.display="flex"}function stopTimer(){clearInterval(interval),stopBtn.style.display="none",startBtn.style.display="flex"}const darkStyles=`
  body, .btn {color: white;}
  h1, .container, footer, .btn {border-color: rgba(255, 255, 255, 0.3);}
  .container, .btn {background-color: rgba(255, 255, 255, 0.1);}
  .btn:hover {border-color: rgba(255, 255, 255, 0.1); background-color: rgba(0, 0, 0, 0.1);}
  .btn:focus {border-color: rgba(255, 255, 255, 0.75); background-color: rgba(0, 0, 0, 0.5);}
`,lightStyles=`
  body, .btn {color: black;}
  h1, .container, footer, .btn {border-color: rgba(0, 0, 0, 0.3);}
  .container, .btn {background-color: rgba(0, 0, 0, 0.1);}
  .btn:hover {border-color: rgba(0, 0, 0, 0.1); background-color: rgba(255, 255, 255, 0.1);}
  .btn:focus {border-color: rgba(0, 0, 0, 0.75); background-color: rgba(255, 255, 255, 0.5);}
`;function getLuminance(t,e,o){let n=[t,e,o].map(function(t){return(t/=255)<=.03928?t/12.92:Math.pow((t+.055)/1.055,2.4)});return .2126*n[0]+.7152*n[1]+.0722*n[2]}function getRandomColor(){let t=getRandomVal(255,1),e=getRandomVal(255,2),o=getRandomVal(255,3),n=getLuminance(t,e,o);return n>.25?styleTag.innerHTML=lightStyles:styleTag.innerHTML=darkStyles,`rgba(${t}, ${e}, ${o})`}function getRandomQuote(){return getRandomVal(quotes.length-1,0)}function createQuote(t=null){let e=getRandomQuote(),o=quotes[e],n;n=t?"rgb(17, 60, 30)":getRandomColor(),body.style.backgroundColor=n;let r=`
    <p class="quote" aria-label="Quote">${o.quote}</p>
    <p class="source" aria-label="Citation">${o.source}
  `;return o.citation&&(r+=`<span class="citation add-prop">${o.citation}</span>`),o.year&&(r+=`<span class="year add-prop">${o.year}</span>`),o.tag&&(r+=`<span class="tag add-prop">${o.tag}</span>`),r+="</p>"}function printQuote(){allBtns.forEach(t=>{t.blur()}),quoteCot.style.transition="opacity 0.5s ease-in 0s",quoteCot.style.opacity=0;let t=createQuote();setTimeout(function(){quoteCot.innerHTML=t,quoteCot.style.transition="opacity 1s ease-out 0s",quoteCot.style.opacity=1},1e3)}if(document.getElementById("enter-site").addEventListener("click",t=>{let e=createQuote(!0);quoteCot.innerHTML=e,setTimeout(function(){document.getElementById("olay").style.display="none",document.getElementsByTagName("header")[0].style.display="flex",document.getElementsByTagName("footer")[0].style.display="flex"},1e3),quoteBkgd.style.display="block",startTimer()}),screen.width>=320){let t=createQuote(!0);quoteCot.innerHTML=t,startTimer()}newBtn.addEventListener("click",t=>{"flex"===stopBtn.style.display?(stopTimer(),printQuote(),startTimer()):printQuote()}),stopBtn.addEventListener("click",stopTimer),startBtn.addEventListener("click",startTimer);